version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    # Load environment variables from the .env file in the project root
    env_file:
      - .env
    ports:
      - "8000:8000" # Expose backend port to host
    volumes:
      - ./backend:/app # Mount backend code for live reload
      - ./backend/prompts:/app/prompts
    environment:
      - WATCHFILES_FORCE_POLLING=true # Necessary for Docker volume watching on some systems

  frontend:
    build: ./frontend
    container_name: svelte_frontend
    ports:
      - "5173:5173" # Expose frontend dev server port to host
    volumes:
      - ./frontend:/app         # Mount frontend code for live reload
      - /app/node_modules     # Use container's node_modules, not host's (important!)
    depends_on:
      - backend # Wait for backend to be available (optional, depends on startup needs)
    stdin_open: true # Keep stdin open for Vite HMR
    tty: true        # Allocate a TTY for Vite HMR 